apiVersion: v1
version: 0.1.0
appVersion: 7.3.4
description: Atlassian Confluence
keywords:
- wiki
maintainers:
- email: thaiph.hust@gmail.com
  name: Thai Pham
name: confluence
sources:
- https://hub.docker.com/r/thaihust/confluence/
