image: thaihust/confluence:7.3.4
imagePullPolicy: IfNotPresent

serviceType: LoadBalancer
ingressDomain: confluence.fago-labs.club

maxMemoryJVM: 1G

resources:
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1

persistence:
  enabled: true
  size: 15Gi
  accessMode: ReadWriteOnce

postgresql:
  imageTag: "9.4"
  cpu: 100m
  memory: 256Mi

  postgresUser: confluence
  postgresPassword: confluence
  postgresDatabase: confluence

  persistence:
    size: 5Gi
